class Menu {
    // eslint-disable-next-line no-useless-constructor
    constructor() {}
    menuList() {
        const menuListData = [{
            modular: '263',
            iconName: 'iconfont icon-gongzuotai3',
            resourceName: '工作台',
            id: '8a8be6ac76e0709d01770447272e00ea',
            menus: [{
                modular: '264',
                iconName: null,
                resourceName: '工作台',
                id: '8a8be6ac76e0709d0177044bee4800eb',
                url: '/home/work_platform',
                permissionName: null
            }],
            url: 'menu-0',
            permissionName: null
        }, {
            modular: '86',
            iconName: 'iconfont icon-zichantaishi',
            resourceName: '态势大屏',
            id: 'ff8080816f89aed4016f89d98f320004',
            menus: [{
                modular: '205',
                iconName: null,
                resourceName: '资产态势',
                id: '8a8be6ac722c1f8401722c2eb54903b3',
                url: '/situation_awareness/assetsFragility',
                permissionName: null
            }, {
                modular: '279',
                iconName: null,
                resourceName: '防御指挥态势',
                id: '8a8be6ac77f099810177f1b824850000',
                url: '/situation_awareness/defenseCommandGK',
                permissionName: null
            }, {
                modular: '280',
                iconName: null,
                resourceName: '指挥调度态势',
                id: '8a8be6ac77f099810177f1b88ae30001',
                url: '/situation_awareness/commandDispatchGK',
                permissionName: null
            }, {
                modular: '329',
                iconName: '',
                resourceName: '大屏数据配置',
                id: '2c9180877b623c3f017b70faff5e0004',
                url: '/home/alarm_data_allocation',
                permissionName: '/manage/viewSet/**'
            }],
            url: 'menu-1',
            permissionName: null
        }, {
            modular: '253',
            iconName: 'iconfont icon-quanbugongdan',
            resourceName: '工单管理',
            id: '8a8be6ac76027f3401761c340b1900e6',
            menus: [{
                modular: '256',
                iconName: null,
                resourceName: '工单模板',
                id: '8a8be6ac76027f3401761c41d5a000e9',
                url: '/home/work_template',
                permissionName: '/manage/workMould/**',
                menus: [{
                    modular: '205',
                    iconName: null,
                    resourceName: '资产态势',
                    id: '8a8be6ac722c1f8401722c2eb54903b3',
                    url: '/situation_awareness/assetsFragility',
                    permissionName: null
                }, {
                    modular: '279',
                    iconName: null,
                    resourceName: '防御指挥态势',
                    id: '8a8be6ac77f099810177f1b824850000',
                    url: '/situation_awareness/defenseCommandGK',
                    permissionName: null
                }, {
                    modular: '280',
                    iconName: null,
                    resourceName: '指挥调度态势',
                    id: '8a8be6ac77f099810177f1b88ae30001',
                    url: '/situation_awareness/commandDispatchGK',
                    permissionName: null
                }, {
                    modular: '329',
                    iconName: '',
                    resourceName: '大屏数据配置',
                    id: '2c9180877b623c3f017b70faff5e0004',
                    url: '/home/alarm_data_allocation',
                    permissionName: '/manage/viewSet/**'
                }]
            }, {
                modular: '254',
                iconName: null,
                resourceName: '全部工单',
                id: '8a8be6ac76027f3401761c412e9d00e7',
                url: '/home/all_work_task',
                permissionName: '/manage/allOrder/**'
            }, {
                modular: '255',
                iconName: null,
                resourceName: '工单任务',
                id: '8a8be6ac76027f3401761c419bd600e8',
                url: '/home/work_task',
                permissionName: '/manage/workOrder/**'
            }, {
                modular: '257',
                iconName: null,
                resourceName: '工单对象',
                id: '8a8be6ac76027f3401761c423d5c00ea',
                url: '/home/work_object',
                permissionName: '/manage/workObject/**'
            }, {
                modular: '326',
                iconName: '',
                resourceName: '工单统计',
                id: '2c9180877aeae530017b2985725b0171',
                url: '/home/work_tab_statistics',
                permissionName: '/manage/workOrderView/**'
            }],
            url: 'menu-2',
            permissionName: null
        }, {
            modular: '232',
            iconName: 'iconfont icon-mobanzhongxin',
            resourceName: '数据中心',
            id: '8a8be6ac752f3a690175447fe7990003',
            menus: [{
                modular: '233',
                iconName: null,
                resourceName: '日志检索',
                id: '8a8be6ac752f3a6901754481a2730004',
                url: '/home/data_center_retrieval/normal',
                permissionName: '/manage/syslog/**'
            }, {
                modular: '243',
                iconName: null,
                resourceName: '数据接入',
                id: '8a8be6ac75df45df0175df8ad86a0000',
                url: '/home/data_center_data_access',
                permissionName: '/manage/dataAccess/**'
            }, {
                modular: '309',
                iconName: '',
                resourceName: '数据解析',
                id: '2c9180847a7fafe0017a83f894500000',
                url: '/home/data_center_parsingRules',
                permissionName: '/manage/logparse/**'
            }, {
                modular: '310',
                iconName: '',
                resourceName: '正则库',
                id: '2c9180847a7fafe0017a83f9b1690001',
                url: '/home/data_center_regularList',
                permissionName: '/manage/regularLibrary/**'
            }, {
                modular: '245',
                iconName: null,
                resourceName: '采集配置库',
                id: '8a8be6ac75df45df0175e374fa6a0002',
                url: '/home/data_center_configuration_library',
                permissionName: '/manage/gatherConfigLibrary/**'
            }, {
                modular: '246',
                iconName: null,
                resourceName: '字段属性',
                id: '8a8be6ac75df45df0175e3b0d99d00de',
                url: '/home/data_center_fieldAttr',
                permissionName: '/manage/logfield/**'
            }, {
                modular: '247',
                iconName: null,
                resourceName: '标签管理',
                id: '8a8be6ac75df45df0175e425a3f401bb',
                url: '/home/data_center_tagList',
                permissionName: '/manage/channelLabel/**'
            }, {
                modular: '290',
                iconName: null,
                resourceName: '日志来源',
                id: '8a8be6ac78442f12017857d3bc9e00ef',
                url: '/home/data_center_log_from',
                permissionName: '/manage/dtConfig/**'
            }, {
                modular: '252',
                iconName: null,
                resourceName: '状态监控',
                id: '8a8be6ac76027f3401760380130c0000',
                url: '/home/data_center_state',
                permissionName: '/manage/monitor/**'
            }],
            url: 'menu-3',
            permissionName: null
        }, {
            modular: '258',
            iconName: 'iconfont icon-baojing',
            resourceName: '告警管理',
            id: '8a8be6ac76b2821b0176d0a2d6720000',
            menus: [{
                modular: '260',
                iconName: null,
                resourceName: '告警列表',
                id: '8a8be6ac76b2821b0176d599af1e00ec',
                url: '/home/alarm_alarm_list',
                permissionName: '/manage/alarmList/**'
            }, {
                modular: '262',
                iconName: null,
                resourceName: '受害资产分析',
                id: '8a8be6ac76b2821b0176d6590ea201d8',
                url: '/home/alarm_asset_analysis',
                permissionName: '/manage/assetsAnalysis/**'
            }, {
                modular: '259',
                iconName: null,
                resourceName: '攻击者分析',
                id: '8a8be6ac76b2821b0176d10ac7d20001',
                url: '/home/alarm_attack_analysis',
                permissionName: '/manage/attackAnalysis'
            }, {
                modular: '261',
                iconName: null,
                resourceName: '告警配置',
                id: '8a8be6ac76b2821b0176d6584bd101d7',
                url: '/home/alarm_tab_alarm_config',
                permissionName: '/manage/alarmConfig/**'
            }],
            url: 'menu-4',
            permissionName: null
        }, {
            modular: '235',
            iconName: 'iconfont icon-guizeguanli',
            resourceName: '规则管理',
            id: '8a8be6ac7567e4f60175923f1c0300da',
            menus: [{
                modular: '236',
                iconName: null,
                resourceName: '分析规则管理',
                id: '8a8be6ac7567e4f6017597488b48027c',
                url: '/home/rule_new_rules_type',
                permissionName: '/manage/rule/**'
            }, {
                modular: '237',
                iconName: null,
                resourceName: '资源池管理',
                id: '8a8be6ac75974eaa0175975216a30000',
                url: '/home/rule_resource_list',
                permissionName: '/manage/resource/**'
            }, {
                modular: '241',
                iconName: null,
                resourceName: '创建模拟数据',
                id: '8a8be6ac75974eaa01759756d8260004',
                url: '/home/rule_simulation',
                permissionName: '/manage/cep/**'
            }],
            url: 'menu-5',
            permissionName: null
        }, {
            modular: '30',
            iconName: 'iconfont icon-zichanzhongxin',
            resourceName: '资产中心',
            id: '30',
            menus: [{
                modular: '160',
                iconName: null,
                resourceName: '资产概览',
                id: '8a8be6ac7124f46c0171337935d30217',
                url: '/home/assets_overview',
                permissionName: '/manage/overviewChart/**'
            }, {
                modular: '43',
                iconName: null,
                resourceName: '指纹库',
                id: '43',
                url: '/home/assets_asset_info',
                permissionName: '/manage/assets/**'
            }, {
                modular: '47',
                iconName: null,
                resourceName: '业务系统管理',
                id: '47',
                url: '/home/assets_system',
                permissionName: '/manage/system/**'
            }, {
                modular: '53',
                iconName: null,
                resourceName: '安全域管理',
                id: '53',
                url: '/home/assets_topology',
                permissionName: '/manage/SafetyZone/**'
            }, {
                modular: '54',
                iconName: null,
                resourceName: '映射管理',
                id: '54',
                url: '/home/assets_mapping',
                permissionName: '/manage/ipLink/**'
            }, {
                modular: '183',
                iconName: null,
                resourceName: '资产配置',
                id: '8a8be6ac718347cc017186f919bc013d',
                url: '/home/assets_type',
                permissionName: '/manage/deviceConfig/**'
            }, {
                modular: '75',
                iconName: null,
                resourceName: '资产发现',
                id: '75',
                url: '/home/assets_found',
                permissionName: '/manage/assetsFind/**'
            }, {
                modular: '78',
                iconName: null,
                resourceName: '拓扑管理',
                id: '78',
                url: '/home/assets_img',
                permissionName: '/manage/topologyImg/**'
            }, {
                modular: '148',
                iconName: null,
                resourceName: '网段管理',
                id: '8a8be6ac711b790a01711bfcd3b30000',
                url: '/home/assets_net_segment',
                permissionName: '/manage/networkSegment/**'
            }],
            url: 'menu-6',
            permissionName: null
        }, {
            modular: '267',
            iconName: 'iconfont icon-weixieqingbao',
            resourceName: '威胁情报',
            id: '8a8be6ac771376ec017713f36b6200d9',
            menus: [{
                modular: '273',
                iconName: null,
                resourceName: '情报查询',
                id: '8a8be6ac7718ab77017727d1ff810374',
                url: '/home/intelligence_threat_database',
                permissionName: '/manage/intelligenceQuery/**'
            }, {
                modular: '274',
                iconName: null,
                resourceName: '威胁情报库',
                id: '8a8be6ac7718ab77017727d22cec0375',
                url: '/home/intelligence_threat_intelligence',
                permissionName: '/manage/intelligence/**'
            }, {
                modular: '275',
                iconName: null,
                resourceName: '采集配置',
                id: '8a8be6ac7718ab77017727d249e60376',
                url: '/home/intelligence_threat_config',
                permissionName: '/manage/collectConfig/**'
            }],
            url: 'menu-7',
            permissionName: null
        }, {
            modular: '266',
            iconName: 'iconfont icon-tongyongloudongku',
            resourceName: '脆弱性',
            id: '8a8be6ac771376ec017713e5591c00d8',
            menus: [{
                modular: '276',
                iconName: null,
                resourceName: '漏洞概览',
                id: '8a8be6ac7718ab770177376a91570459',
                url: '/home/leak_overview',
                permissionName: '/manage/overview/**'
            }, {
                modular: '270',
                iconName: null,
                resourceName: '漏洞管理',
                id: '8a8be6ac7718ab77017719e3ced700db',
                url: '/home/leak_leak',
                permissionName: '/manage/scanLeak/**'
            }, {
                modular: '269',
                iconName: null,
                resourceName: '漏洞信息库',
                id: '8a8be6ac7718ab770177192b57280000',
                url: '/home/leak_loophole',
                permissionName: '/manage/leakInfo/**'
            }, {
                modular: '272',
                iconName: null,
                resourceName: '任务管理',
                id: '8a8be6ac7718ab7701771eb6f9480294',
                url: '/home/leak_task',
                permissionName: '/manage/taskInfo/**'
            }, {
                modular: '268',
                iconName: null,
                resourceName: '引擎管理',
                id: '8a8be6ac771376ec017714a3434b00da',
                url: '/home/leak_engine',
                permissionName: '/manage/scanEngine/**'
            }, {
                modular: '271',
                iconName: null,
                resourceName: '标签管理',
                id: '8a8be6ac7718ab7701771e648c9001b7',
                url: '/home/leak_label',
                permissionName: '/manage/labelInfo/**'
            }],
            url: 'menu-8',
            permissionName: null
        }, {
            modular: '226',
            iconName: 'iconfont icon-baobiaozhongxin',
            resourceName: '报表中心',
            id: '8a8be6ac747c7a2301749581cd9a0003',
            menus: [{
                modular: '227',
                iconName: null,
                resourceName: '报表任务',
                id: '8a8be6ac747c7a2301749583752e0004',
                url: '/home/report_form_task',
                permissionName: '/manage/reportTask/**'
            }, {
                modular: '228',
                iconName: null,
                resourceName: '报表模板',
                id: '8a8be6ac747c7a23017495df893600cf',
                url: '/home/report_form_template',
                permissionName: '/manage/reportMould/**'
            }],
            url: 'menu-9',
            permissionName: null
        }, {
            modular: '12',
            iconName: 'iconfont icon-yanlianzhongxin',
            resourceName: '演练中心',
            id: '12',
            menus: [{
                modular: '162',
                iconName: null,
                resourceName: '演练概览',
                id: '8a8be6ac7124f46c0171345c4c02032d',
                url: '/home/defense_drill_overview',
                permissionName: '/manage/overviewChart/**'
            }, {
                modular: '17',
                iconName: null,
                resourceName: '演练任务',
                id: '17',
                url: '/home/defense_drill_match',
                permissionName: '/manage/gameEvent/**'
            }, {
                modular: '18',
                iconName: null,
                resourceName: '攻击方成果',
                id: '18',
                url: '/home/defense_drill_record',
                permissionName: '/manage/record/**'
            }, {
                modular: '28',
                iconName: null,
                resourceName: '防守方成果',
                id: '28',
                url: '/home/defense_drill_defense_record',
                permissionName: '/manage/record/**'
            }, {
                modular: '59',
                iconName: null,
                resourceName: '指挥交流大厅',
                id: '59',
                url: '/home/defense_drill_chat',
                permissionName: '/manage/greeting/**'
            }, {
                modular: '81',
                iconName: null,
                resourceName: '演练复盘',
                id: '81',
                url: '/home/defense_drill_replay',
                permissionName: '/manage/rehearsal/**'
            }, {
                modular: '305',
                iconName: 'iconfont icon-gongjifangchengguo1',
                resourceName: '攻击方成果(裁判)',
                id: '8a8be6ac79f3d8270179f481a6930349',
                url: '/home/defense_drill_record_referee',
                permissionName: '/manage/attackReferee/**'
            }, {
                modular: '306',
                iconName: 'iconfont icon-fangshoufangchengguo1',
                resourceName: '防守方成果(裁判)',
                id: '8a8be6ac79f3d8270179f4823143034a',
                url: '/home/defense_drill_defense_record_referee',
                permissionName: '/manage/defenseReferee/**'
            }],
            url: 'menu-10',
            permissionName: null
        }, {
            modular: '163',
            iconName: 'iconfont icon-baoloumianfenxi',
            resourceName: '暴露面分析',
            id: '8a8be6ac7139f45a01713a2073dc0001',
            menus: [{
                modular: '164',
                iconName: null,
                resourceName: '任务管理',
                id: '8a8be6ac7139f45a01713a21f5770002',
                url: '/home/free_face_task',
                permissionName: '/manage/facetask/**'
            }, {
                modular: '167',
                iconName: null,
                resourceName: '企业暴露面',
                id: '8a8be6ac7139f45a01713a23461f0005',
                url: '/home/free_face_exposeList',
                permissionName: '/manage/enterprise/**'
            }],
            url: 'menu-11',
            permissionName: null
        }, {
            modular: '282',
            iconName: 'iconfont icon-gongjifenxi',
            resourceName: '钓鱼邮件',
            id: '8a8be6ac7801a1db017833a2c87e0001',
            menus: [{
                modular: '283',
                iconName: null,
                resourceName: '钓鱼概览',
                id: '8a8be6ac7801a1db01783e078ae70002',
                url: '/home/phishing_overview',
                permissionName: '/manage/overview/**'
            }, {
                modular: '285',
                iconName: null,
                resourceName: '邮件分析',
                id: '8a8be6ac7801a1db01783e08a96c0004',
                url: '/home/phishing_eamil_email_analysis',
                permissionName: '/manage/emailAnalysis/**'
            }, {
                modular: '284',
                iconName: null,
                resourceName: '告警管理',
                id: '8a8be6ac7801a1db01783e0841150003',
                url: '/home/phishing_alarm',
                permissionName: '/manage/report/**'
            }, {
                modular: '292',
                iconName: null,
                resourceName: '资源池管理',
                id: '8a8be6ac78674fa101786dca882100f1',
                url: '/home/phishing_resource_list',
                permissionName: '/manage/resource/**'
            }, {
                modular: '286',
                iconName: null,
                resourceName: '白名单',
                id: '8a8be6ac7801a1db01783e0980ec0005',
                url: '/home/phishing_eamil_white_list',
                permissionName: '/manage/white/**'
            }, {
                modular: '287',
                iconName: null,
                resourceName: '黑名单',
                id: '8a8be6ac7801a1db01783e0b3f860006',
                url: '/home/phishing_eamil_black_list',
                permissionName: '/manage/black/**'
            }, {
                modular: '289',
                iconName: null,
                resourceName: '创建模拟数据',
                id: '8a8be6ac78442f12017849823be00000',
                url: '/home/phishing_simulation',
                permissionName: null
            }],
            url: 'menu-12',
            permissionName: null
        }, {
            modular: '99',
            iconName: 'iconfont icon-mobanzhongxin',
            resourceName: '指挥调度',
            id: '8a8be6ac703086200170877e1ccb0000',
            menus: [{
                modular: '100',
                iconName: null,
                resourceName: '区域坐席',
                id: '8a8be6ac7030862001708852a89c0005',
                url: '/home/protect_net_region',
                permissionName: '/manage/seatArea/**'
            }, {
                modular: '153',
                iconName: null,
                resourceName: '组织架构列表',
                id: '8a8be6ac7124f46c0171294b09de0004',
                url: '/home/protect_net_organization',
                permissionName: '/manage/organization/**'
            }, {
                modular: '157',
                iconName: null,
                resourceName: '作战室排班列表',
                id: '8a8be6ac7124f46c0171314b68f6018c',
                url: '/home/protect_net_fightSchedule',
                permissionName: '/manage/workforcemanage/**'
            }, {
                modular: '158',
                iconName: null,
                resourceName: '规则规范记录列表',
                id: '8a8be6ac7124f46c0171314ecc0a018d',
                url: '/home/protect_net_ruleStandard',
                permissionName: '/manage/discilinrule/**'
            }, {
                modular: '180',
                iconName: null,
                resourceName: '任务列表',
                id: '8a8be6ac717741b4017182518c080001',
                url: '/home/protect_net_baseTask',
                permissionName: '/manage/baseTask/**'
            }, {
                modular: '181',
                iconName: null,
                resourceName: '我的任务',
                id: '8a8be6ac718347cc0171863d6b2f0000',
                url: '/home/protect_net_myTask',
                permissionName: '/manage/myTask/**'
            }, {
                modular: '182',
                iconName: null,
                resourceName: '回收站',
                id: '8a8be6ac718347cc01718676f918009e',
                url: '/home/protect_net_recycle',
                permissionName: '/manage/recovery/**'
            }],
            url: 'menu-13',
            permissionName: null
        }, {
            modular: '307',
            iconName: 'iconfont icon-zhihuijiaoliudating',
            resourceName: '聊天管理',
            id: '2c9180847a5bda3a017a5c1b8be10001',
            menus: [{
                modular: '308',
                iconName: '',
                resourceName: '聊天室大厅',
                id: '2c9180847a5bda3a017a5c1be25f0002',
                url: '/home/chat_room',
                permissionName: '/manage/chatroom/**'
            }],
            url: 'menu-14',
            permissionName: null
        }, {
            modular: '325',
            iconName: 'iconfont icon-yunyingguanli',
            resourceName: '联动管理',
            id: '2c9180847ace5967017ad125d7bd0000',
            menus: [{
                modular: '316',
                iconName: '',
                resourceName: 'NFT管理',
                id: '2c9180847ace5967017ad12647a40001',
                url: '/home/linkage_nft',
                permissionName: '/manage/nft/**'
            }, {
                modular: '317',
                iconName: '',
                resourceName: 'TAR管理',
                id: '2c9180847ace5967017ad1269aec0002',
                url: '/home/linkage_tar',
                permissionName: '/manage/tar/**'
            }, {
                modular: '319',
                iconName: '',
                resourceName: '时间配置',
                id: '2c9180847ace5967017ad127c0bd0004',
                url: '/home/linkage_time_config',
                permissionName: '/manage/timeConfig/**'
            }],
            url: 'menu-15',
            permissionName: null
        }, {
            modular: '13',
            iconName: 'iconfont icon-pingtaiweihu1',
            resourceName: '系统管理',
            id: '13',
            menus: [{
                modular: '7',
                iconName: null,
                resourceName: '角色管理',
                id: '7',
                url: '/home/role',
                permissionName: '/manage/userRole/**'
            }, {
                modular: '8',
                iconName: null,
                resourceName: '用户管理',
                id: '8',
                url: '/home/user',
                permissionName: '/manage/adminUser/**'
            }, {
                modular: '14',
                iconName: null,
                resourceName: '部门管理',
                id: '14',
                url: '/home/department',
                permissionName: '/manage/department/**'
            }, {
                modular: '27',
                iconName: null,
                resourceName: '功能模块管理',
                id: '27',
                url: '/home/module',
                permissionName: '/manage/modular/**'
            }, {
                modular: '230',
                iconName: null,
                resourceName: '资产用户管理',
                id: '8a8be6ac7520d3cf01752104877f0000',
                url: '/home/asset_users',
                permissionName: '/manage/assetsUser/**'
            }, {
                modular: '249',
                iconName: null,
                resourceName: '基础输出配置',
                id: '8a8be6ac75f4ef3f0175f88fe9270000',
                url: '/home/system_params',
                permissionName: '/manage/platformConfig/**'
            }, {
                modular: '288',
                iconName: null,
                resourceName: '主题设置',
                id: '8a8be6ac7801a1db01784420aee601df',
                url: '/home/theme_config',
                permissionName: '/manage/themeConfig/**'
            }, {
                modular: '328',
                iconName: '',
                resourceName: '升级管理',
                id: '2c9180877b529bce017b57131a960178',
                url: '/home/upgrade',
                permissionName: '/manage/upModule/**'
            }],
            url: 'menu-16',
            permissionName: null
        }]
        return menuListData
    }
}
export default new Menu()
